### ISSUE TITLE
目的是让 createViewHolder 和 bindViewHolder 在子线程完成吗？

### ISSUE THREAD

**Issue by pdog18** [shineM/RecyclerViewCacheDemo#1]
如果是这样的话，因为在 ViewCacheExtension 获取的 View 可能因为此时还没有 attach 到 RecyclerView 上，这样的确不会触发到 ViewRootImpl#checkThread()。

但是这样做好像有个隐患，比如用户进行了必须要在主线程执行的操作，（进行了 Handler 的创建，比如 FakeView 有个 Handler 成员变量），这时候就会 Crash 了。

**Comment by shineM** [comment]
对，所以我这个 demo 只是提供一个思路，并不建议在生产环境使用，除非能确保 create 和 bind 全部操作都能在子线程进行

**Comment by pdog18** [comment]
谢谢您的回复，这个思路挺有趣的。最近在找这个 ViewCacheExtension 的用处，找遍全网好像只有您这一个，后来您有遇到别的有效案例吗？

**Comment by shineM** [comment]
个人看来这个 API 适合对缓存有较高自定义程度的场景，一般不会用到
